// <auto-generated />
using IHUS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IHUS.Database.Migrations
{
    [DbContext(typeof(IHUSDbContext))]
    partial class IHUSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IHUS.Database.Entities.ShortenedUrlEntity", b =>
                {
                    b.Property<string>("ShortUrlKey")
                        .HasColumnType("character(6)");

                    b.Property<string>("ActualUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("ShortUrlKey");

                    b.ToTable("ShortenedUrls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
